config/routes.rb
Rails.application.routes.draw do
  resources:about
  resources:contact
  resources:campaign
  resources:collection
  get 'simple_pages/index'
  get 'simple_pages/index'
  get 'simple_pages/index'
  get 'simple_pages/index'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController
  def index
  end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="container_about" id= "about">
      <div class="About">
        <div class="col-md-6 col-xs-12 col-lg-6 col-sm-12">
          <div class="Image_column">
            <%= image_tag("xxx.jpg", class: "img-responsive my-image1") %>
          </div><!-- end image -->
        </div>
        <div class="col-md-6 col-xs-12 col-lg-6 col-sm-12">
          <div class="History_of_the_brand_Maia">
            <h1> History of the brand Maia </h1>
              <p>From when I was very young, my interest in fashion was always present, which also got me interested in drawing from a young age. Colors and the way they merge together and kind of change your own mood were especially always fascinating for me. The creation of something that has never been there before and the skill to develop something with your own hands were the most important part of drawing for me.  Being creative is essential in order to design successfull clothes and creativity was therefore the fundament on which I built the development of my fashion brand. We are currently at the beginning stages of our brand development and planning to launch our very first collection in July 2018. The first collection will contain two different long-arm jumpsuits as well as a long-arm dress. The collection will be for autum/winter 2018 and is therefore in wintery colours as well as off-white. For the beginning, we will start selling our collection in 4 different boutiques in frankfurt and will thereafter be present in more and more boutiques.</p>

            <h1>Our vision at Maia</h1>
              <p>In a world where being dressed nice becomes more and more important, the feeling of being comfortable within your own skin, should always be considered as well. We at Maia only use luxurious fabrics like silk and cashmere in order to make the woman, who wears our designs feel like a fairytale. All our cuts are flirty and loose in order to allow the woman, who wears it, to move freely and not be restricted by any narrow design. Furthermore, we use rich and colorful patterns in order to make a rainy day shiny and more bearable. </p>
          </div>
        </div>
      </div>
    </div><!-- end container_about-->
  </body>
</html>

app/views/campaign/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/b68cSioKz-8"></iframe>
    </div>
  </body>
</html>

app/views/collection/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class="New_york">
      <p>Pull the arrows right and left to see more</p>
    </div>
  </head>
  <body>
    <div class="modal-body">
      <div id="myGallery" class="carousel slide" data-interval="false">
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag("slideshow2.PNG", class: "img-responsive my-image1") %>
          </div>
          <div class="item">
            <%= image_tag("slideshow1.PNG", class: "img-respponsive my-image2") %>
          </div>
          <div class="item">
            <%= image_tag("slideshow3.PNG", class: "img-respponsive my-image3") %>
          </div>
        </div><!--end carousel-inner-->
          <!-- Previous and Next buttons-->
        <div class="Buttons">
          <a class="left carousel-control" href="#myGallery" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#myGallery" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
      </div><!-- myGallery-->
    </div><!-- modal-body-->
  </body>
</html>

app/views/contact/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class= "Picture">
      <%= image_tag("www.jpg", class: "img-responsive") %>
    </div><!-- end Picture-->
  </head>
  <body>
    <div class= "placer" id= "contact">
      <div class="header_contact">
        <h1> Contact</h1>
      </div><!-- end header -->
      <div class="Text">
        <p> If you want to know more about our collection and lable, feel free to contact me at any time. </p>
      </div><!-- end Text -->
      <div class="Mail">
        <p>Jessica.zdralek@gmx.de</p>
      </div><!--end Mail-->
      <div class="Text2">
        <p> If time urgency is high, please feel free to call me. </p>
      </div><!-- Text2 -->
      <div class="Phonenumber">
        <p> 015234275420</p>
      </div><!--end Phone number-->
      <div class="Location">
        <p><a class="btn btn-default" href="https://www.google.de/maps/place/Moritzstra%C3%9Fe+20,+65185+Wiesbaden/@50.075574,8.2365761,17z/data=!3m1!4b1!4m5!3m4!1s0x47bdbde08c2cf18f:0xe49e0da2e4f19acf!8m2!3d50.0755706!4d8.238770" role="button">Google Maps &raquo;</a></p>
        <p><a class="btn btn-default" href="https://www.facebook.com/jessica.zdralek.7" role="button">Facebook &raquo;</a></p>
      </div>
    </div><!-- end Placer -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maia</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Courgette">
  </head>
  <body>
    <!--navbar starts here-->
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container-fluid">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <div class="project">
             <header><a><%= link_to "Maia", root_path %></a></header>
           </div> <!--end projectName -->
         </div> <!--end navbar-header -->
         <div class="navbar-collapse collapse">
           <ul class="nav navbar-nav navbar-right">
           <li><a><%= link_to "Home", root_path %></a></li>
           <li><a><%= link_to "Campaign", campaign_index_path %></a></li>
           <li><a><%= link_to "Collection", collection_index_path %></a></li>
           <li><a><%= link_to "About", about_index_path %></a></li>
           <li><a><%= link_to "Contact", contact_index_path %></a></li>
           </ul>
         </div> <!--nav-->
       </div> <!-- end nav container-->
     </nav><!-- end navbar-->
    <%= yield %>
    <footer>
      <div class="copyright">
        &copy; 2018 Maia
      </div>
   </footer>
  </body>
</html>

app/views/simple_pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= image_tag("hallo.jpg", class: "img-responsive") %>
  </head>
  <div class= "greeting">
    <h2>Welcome to the fashion lable called "Maia"</h2>
      <p>Your fashion brand for fairylike and luxurious fashion</p>
  </div>
</html>